import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#005077",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#00504a",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed": "#001e30",
        "surface-bright": "#f7f9fb",
        "error-container": "#ffdad6",
        "surface-container-high": "#e6e8ea",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#264191",
        "tertiary-fixed-dim": "#5adace",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#004b71",
        "secondary-fixed": "#cbe6ff",
        "on-tertiary-container": "#37bfb3",
        "primary-container": "#1e3a8a",
        "on-primary-container": "#90a8ff",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b6c4ff",
        "surface-container": "#eceef0",
        background: "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "on-background": "#191c1e",
        "outline-variant": "#c5c5d3",
        "on-error-container": "#93000a",
        primary: "#00236f",
        "on-tertiary-fixed": "#00201d",
        "on-primary-fixed": "#00164e",
        "secondary-container": "#74c3fe",
        "surface-container-low": "#f2f4f6",
        "on-error": "#ffffff",
        "on-surface-variant": "#444651",
        "tertiary-fixed": "#79f7ea",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        outline: "#757682",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed-dim": "#b6c4ff",
        "inverse-surface": "#2d3133",
        "secondary-fixed-dim": "#8ecdff",
        "surface-tint": "#4059aa",
        "on-secondary": "#ffffff",
        tertiary: "#00312d",
        surface: "#f7f9fb",
        secondary: "#006494",
        "primary-fixed": "#dce1ff",
        "tertiary-container": "#004944",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        sans: ["var(--font-cairo)", "sans-serif"],
        headline: ["var(--font-cairo)", "sans-serif"],
        body: ["var(--font-cairo)", "sans-serif"],
        label: ["var(--font-cairo)", "sans-serif"],
      },
      keyframes: {
        "fade-up-soft": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "partner-logo-in": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-up-soft": "fade-up-soft 0.85s cubic-bezier(0.22, 1, 0.36, 1) both",
        "partner-logo-in": "partner-logo-in 0.58s cubic-bezier(0.22, 1, 0.36, 1) both",
      },
    },
  },
  plugins: [],
};

export default config;
